{% set name = "ark" %}
{% set version = "0.1.144" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/{{ version }}.tar.gz
  sha256: 9688bd97eaf949809b7ae5a38241bc6e85883107b9ce9a7a63a58e27928126bf

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses

test:
  commands:
    - ark --version

about:
  home: https://github.com/posit-dev/ark
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  dev_url: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
