{% set name = "ark" %}
{% set version = "0.1.153" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/{{ version }}.tar.gz
  sha256: 75e6c5c145337fea7a861017a1340956c3fbb56aa46e66f5b195acc29bcab649

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - ark --help 2>&1 | grep -q "A connection file must be specified."

about:
  home: https://github.com/posit-dev/ark
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  dev_url: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
