context:
  version: "0.1.233"

package:
  name: ark
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/${{ version }}.tar.gz
  sha256: b9159a722301878aedc24508047016c74c2f40c5f3cdba53968c21942d312c82

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - git

tests:
  - script:
      - ark --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  homepage: https://github.com/posit-dev/ark
  repository: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
