context:
  version: "0.1.245"

package:
  name: ark
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/${{ version }}.tar.gz
  sha256: 38783a1843cf342dcc3565ce80e18d80b5e5808c316035ba44ae392afe2ba4e3

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - git

tests:
  - script:
      - ark --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  homepage: https://github.com/posit-dev/ark
  repository: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
