context:
  version: "0.1.173"

package:
  name: ark
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/${{ version }}.tar.gz
  sha256: da0d8d24f15f09c5d12545d1bd2c4b2a62a6cc88719eb006a05c663480407bc0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - "ark --help 2>&1 | grep -q \"A connection file must be specified.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  homepage: https://github.com/posit-dev/ark
  repository: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
