context:
  version: "0.1.244"

package:
  name: ark
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/${{ version }}.tar.gz
  sha256: 897c42cfa50cff78ace2013d7ee516c1b57667cb64ad2fefd86df8b485ec4ba4

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - git

tests:
  - script:
      - ark --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  homepage: https://github.com/posit-dev/ark
  repository: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
