context:
  version: "0.1.193"

package:
  name: ark
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/${{ version }}.tar.gz
  sha256: 9b15bc60f7b83c31a7133ee6916651b5845ce3f649d17756d27948164704598e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - "ark --help 2>&1 | grep -q \"A connection file must be specified.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  homepage: https://github.com/posit-dev/ark
  repository: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
