context:
  version: "0.1.186"

package:
  name: ark
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/ark/archive/${{ version }}.tar.gz
  sha256: f9914b0dd88666ed6cc2c1014f591c3f2eb1709a67df052de9d2e92d83823c53

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - "ark --help 2>&1 | grep -q \"A connection file must be specified.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Ark, an R kernel
  homepage: https://github.com/posit-dev/ark
  repository: https://github.com/posit-dev/ark

extra:
  recipe-maintainers:
    - danielnachun
